Repository DSC-ASEB/Hacktoberfest, pull requests merged in 2021-10, with the labels that each got.

#25 Create Windows_logo.py
  Python/Windows_logo.py
Labels: size/S

#28 Update README.md
  README.md
Labels: size/S

#27 Added printing patterns in C++
  C++/README.md
  C++/patterns/README.md
  C++/patterns/binaryHalfPyramid.cpp
  C++/patterns/diamondInscribedRectangle.cpp
  C++/patterns/flipHalfPyramid.cpp
  C++/patterns/floydsTriangle.cpp
  C++/patterns/halfPyramid.cpp
  C++/patterns/hollowButterfly.cpp
  C++/patterns/hollowDiamond.cpp
  C++/patterns/hollowRectangle.cpp
  C++/patterns/hollowRhombus.cpp
  C++/patterns/invHalfPyramid.cpp
  C++/patterns/numbHalfPyramid.cpp
  C++/patterns/numbHalfPyramid2.cpp
  C++/patterns/numbInvHalfPyramid.cpp
  C++/patterns/numbInvHalfPyramid2.cpp
  C++/patterns/numbPyramid.cpp
  C++/patterns/numbPyramid2.cpp
  C++/patterns/palindromePyramid.cpp
  C++/patterns/pascalTriangle.cpp
  C++/patterns/solidButterfly.cpp
  C++/patterns/solidDiamond.cpp
  C++/patterns/solidRectangle.cpp
  C++/patterns/solidRhombus.cpp
  C++/patterns/zigzag.cpp
Labels: size/XXL

#15 Added new gif_gen files
  JavaScript/gif_gen/README.md
  JavaScript/gif_gen/gif.css
  JavaScript/gif_gen/gif.html
  JavaScript/gif_gen/gif.js
Labels: size/M

#29 Face & Eye Detector
  Python/face_eye_detector/README.md
  Python/face_eye_detector/code.py
  Python/face_eye_detector/haarcascade_eye.xml
  Python/face_eye_detector/haarcascade_frontalface_default.xml
Labels: size/XXL, hacktoberfest-accepted

#26 Added a C++ program to implement OOPs for a box
  C++/Kanishkasrivastavahacktoberfest.cpp
Labels: size/L

#33 Create fibonnaciSequence.py
  Python/fibonnaciSequence.py
Labels: size/S
