Repository DSC-ASEB/Hacktoberfest, pull requests merged in 2021-11, with the labels that each got.

#35 Find surface area and volume of cube
  Java/CubeVolumeAndArea.java
Labels: size/S

#36 Inventory Management System using Python
  Python/IMS/Inventory_Management_System.ipynb
  Python/IMS/README.md
  Python/IMS/Records.json
  Python/IMS/Sales.json
Labels: size/XL

#21 Simple webpage using anime.js
  JavaScript/moon_animation/README.md
  JavaScript/moon_animation/images/moon.png
  JavaScript/moon_animation/images/mountains_behind.png
  JavaScript/moon_animation/images/mountains_front.png
  JavaScript/moon_animation/images/stars.png
  JavaScript/moon_animation/index.html
  JavaScript/moon_animation/style.css
Labels: size/L
